apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.imagepath }}:{{ .Values.image_version }}
          env:
            - name: DB_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-database.{{ .Release.Namespace }}.svc.cluster.local:5432/mydb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PWD
              value: "postgres"
          ports:
            - containerPort: 8080
              protocol: TCP
