apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.global.hostname }}`) && PathPrefix(`/api`)
      middlewares:
        - name: {{ .Release.Name }}-middleware
      services:
        - kind: Service
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          port: 8080
          scheme: http
