apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: postgres:16
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: {{ .Values.global.Database.DB_USER | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.global.Database.DB_PWD | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.global.Database.SCHEMA }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

