apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: client-react-nginx
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.global.hostname }}`)
      services:
        - kind: Service
          name: client-react-nginx
          port: 80
          scheme: http